<?php
/**
* @file
* Webform module to submit to Blue Hornet email system
*/

/**
 * Implements hook_menu().
 */
function bluehornet_menu() {
  $items = array();

  $items['admin/config/services/bluehornet'] = array(
    'title' => 'Bluehornet',
    'description' => 'Configuration for Bluehornet module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bluehornet_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: Current posts settings
 *
 * @see bluehornet_menu()
 */
function bluehornet_form($form, &$form_state) {
  $form['bluehornet_cid'] = array(
    '#type' => 'textfield',
    '#title' => t('Bluehornet CID'),
    '#default_value' => variable_get('bluehornet_cid'),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Bluehornet Client ID Code'),
    '#required' => TRUE,
  );
  
  $form['bluehornet_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Bluehornet URL'),
    '#default_value' => variable_get('bluehornet_url'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Bluehornet Account Submission URL'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_permission().
 */
function bluehornet_permission() {
  return array(
    'access bluehornet content' => array(
      'title' => t('Access content for the Bluehornet module'),
    )
  );
}

/**
* Submit to Blue Hornet once Webform submission is complete 
*/
function bluehornet_webform_submission_insert($node, $submission) {

  //System variables
  $url = variable_get('bluehornet_url');
  $cid = variable_get('bluehornet_cid');  
  $group = variable_get('bluehornet_group');

  $firstname = $_POST['submitted']['first_name'];
  $lastname = $_POST['submitted']['last_name'];
  $email = $_POST['submitted']['email'];
  $postal = $_POST['submitted']['postal_code'];
  $rfid = $_POST['submitted']['rfid'];

  $myvars = 'firstname=' . $firstname . '&lastname=' . $lastname . '&cid=' . $cid . '&email=' . $email . '&postal_code=' . $postal . '&field_array[249598]=' . $rfid . '&grp[]=' . $group;

  print($url . '?' . $myvars);
  exit;
  // $ch = curl_init($url);
//   curl_setopt($ch, CURLOPT_POST, 1);
//   curl_setopt($ch, CURLOPT_POSTFIELDS, $myvars);
//   curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
//   curl_setopt($ch, CURLOPT_HEADER, 0);
//   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
//   $response = curl_exec($ch);
}
