<?php
/**
 * @file
 * Webform module to submit to Blue Hornet email system
 */

/**
 * Implements hook_menu().
 */
function bluehornet_menu() {
  $items = array();

  $items['admin/config/services/bluehornet'] = array(
    'title' => 'Bluehornet',
    'description' => 'Configuration for Bluehornet module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bluehornet_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['node/%webform_menu/webform/bluehornet'] = array(
    'title' => 'Bluehornet',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bluehornet_local_form'),
    'access arguments' => array('access administration pages'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Page callback: Bluehornet settings
 *
 * @see bluehornet_menu()
 */
function bluehornet_form($form) {
  $form['bluehornet_cid'] = array(
    '#type' => 'textfield',
    '#title' => t('Bluehornet CID'),
    '#default_value' => variable_get('bluehornet_cid'),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Bluehornet Client ID Code'),
    '#required' => TRUE,
  );

  $form['bluehornet_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Bluehornet URL'),
    '#default_value' => variable_get('bluehornet_url'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Bluehornet Account Submission URL'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


/**
 *Add Bluehornet Specific Elements
 *
 **/

function bluehornet_local_form($form) {

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nodeid = arg(1);
  } else {
    $nodeid = null;
  }

  $form['bluehornet_group_node_' . $nodeid] = array(
    '#type' => 'textfield',
    '#title' => t('Group ID'),
    '#default_value' => variable_get('bluehornet_group_node_' . $nodeid),
    '#size' => 6,
    '#maxlength' => 6,
    '#description' => t('6 Digit Segment ID Identifier'),
    '#required' => TRUE,
  );

  $form ['bluehornet_rfid_node_' . $nodeid] = array(
    '#type' => 'textfield',
    '#title' => t('RFID Identifier'),
    '#default_value' => variable_get('bluehornet_rfid_node_' . $nodeid),
    '#size' => 6,
    '#maxlength' => 6,
    '#description' => t('6 Digit RFID Identifier, Found in Bluehornet. <i>&field_array[XXXXXX]</i>'),
    '#required' => FALSE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_permission().
 */
function bluehornet_permission() {
  return array(
    'access bluehornet content' => array(
      'title' => t('Access content for the Bluehornet module'),
    )
  );
}

/**
 * Submit to Blue Hornet once Webform submission is complete
 */
function bluehornet_webform_submission_insert($node, $submission) {

  $nid = $node->nid;
  $sid = $submission->sid;

  //System variables
  $url = variable_get('bluehornet_url');
  $cid = variable_get('bluehornet_cid');
  $group = variable_get('bluehornet_group_node_' . $nid);
  $rfid_id = variable_get('bluehornet_rfid_node_' . $nid);

  $firstname = $_POST['submitted']['first_name'];
  $lastname = $_POST['submitted']['last_name'];
  $email = $_POST['submitted']['email'];
  $postal = $_POST['submitted']['postal_code'];
  $rfid = $_POST['submitted']['rfid'];

  $myvars = 'firstname=' . $firstname . '&lastname=' . $lastname . '&cid=' . $cid . '&email=' . $email . '&postal_code=' . $postal . '&field_array[' . $rfid_id . ']=' . $rfid . '&grp[]=' . $group;

  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $myvars);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  $response = curl_exec($ch);

  //Log the response in Drupal
  if ($response) {
    watchdog('Bluehornet Webform SID - ' . $sid, $response);
  }
}